/* eslint-disable global-require */
/**
* @author GNURT
* @flow
*/

const images = {
  bg_account: require('../assets/images/bg_account.png'),
  ic_account_active: require('../assets/images/ic_account_active.png'),
  ic_account_normal: require('../assets/images/ic_account_normal.png'),
  ic_add: require('../assets/images/ic_add.png'),
  ic_add_cart: require('../assets/images/ic_add_cart.png'),
  ic_arrow_up: require('../assets/images/ic_arrow_up.png'),
  ic_back: require('../assets/images/ic_back.png'),
  ic_bag_active: require('../assets/images/ic_bag_active.png'),
  ic_bag_normal: require('../assets/images/ic_bag_normal.png'),
  ic_bookmark: require('../assets/images/ic_bookmark.png'),
  ic_calendar: require('../assets/images/ic_calendar.png'),
  ic_campain: require('../assets/images/ic_campain.png'),
  ic_cart: require('../assets/images/ic_cart.png'),
  ic_category_active: require('../assets/images/ic_category_active.png'),
  ic_category_normal: require('../assets/images/ic_category_normal.png'),
  ic_change_password: require('../assets/images/ic_change_password.png'),
  ic_checked: require('../assets/images/ic_checked.png'),
  ic_close: require('../assets/images/ic_close.png'),
  ic_copy: require('../assets/images/ic_copy.png'),
  ic_delete: require('../assets/images/ic_delete.png'),
  ic_dollar: require('../assets/images/ic_dollar.png'),
  ic_download: require('../assets/images/ic_download.png'),
  ic_dropdown: require('../assets/images/ic_dropdown.png'),
  ic_edit: require('../assets/images/ic_edit.png'),
  ic_edit_customer: require('../assets/images/ic_edit_customer.png'),
  ic_eye: require('../assets/images/ic_eye.png'),
  ic_guest: require('../assets/images/ic_guest.png'),
  ic_help: require('../assets/images/ic_help.png'),
  ic_home_active: require('../assets/images/ic_home_active.png'),
  ic_home_normal: require('../assets/images/ic_home_normal.png'),
  ic_info: require('../assets/images/ic_info.png'),
  ic_info_account: require('../assets/images/ic_info_account.png'),
  ic_location: require('../assets/images/ic_location.png'),
  ic_logo_app: require('../assets/images/ic_logo_app.png'),
  ic_logout: require('../assets/images/ic_logout.png'),
  ic_minus: require('../assets/images/ic_minus.png'),
  ic_more: require('../assets/images/ic_more.png'),
  ic_note: require('../assets/images/ic_note.png'),
  ic_notification_normal: require('../assets/images/ic_notification_normal.png'),
  ic_order: require('../assets/images/ic_order.png'),
  ic_post: require('../assets/images/ic_post.png'),
  ic_post_active: require('../assets/images/ic_post_active.png'),
  ic_register_colaborator_success: require('../assets/images/ic_register_colaborator_success.png'),
  ic_search: require('../assets/images/ic_search.png'),
  ic_search_category: require('../assets/images/ic_search_category.png'),
  ic_share: require('../assets/images/ic_share.png'),
  ic_show_pass: require('../assets/images/ic_show_pass.png'),
  ic_trash: require('../assets/images/ic_trash.png'),
  ic_uncheck: require('../assets/images/ic_uncheck.png'),
  ic_upload: require('../assets/images/ic_upload.png'),
  ic_user: require('../assets/images/ic_user.png'),
  ic_voucher: require('../assets/images/ic_voucher.png'),
  ic_wallet_success: require('../assets/images/ic_wallet_success.png'),
  none_data: require('../assets/images/none_data.gif'),
  rectangle: require('../assets/images/rectangle.png'),
};
export default images;
