export default {
  LOGIN: 'LOGIN',
  SAVE_LOGIN: 'SAVE_LOGIN',
  SELECT_POSITION: 'SELECT_POSITION',
  LOGOUT: 'LOGOUT',
  ADD_COUNT_CART: 'ADD_COUNT_CART',
  SAVE_TIME_SHOW_POPUP: 'SAVE_TIME_SHOW_POPUP',
  SAVE_ENUMS: 'SAVE_ENUMS',
};
